/** @type {import('tailwindcss').Config} */
module.exports = {
    darkMode: 'class',
    content: ['./src/**/*.{html,js,jsx,ts,tsx}'],
    theme: {
        extend: {
            colors: {
                // Brand token used for utility classes like bg-primary/10, text-primary, etc.
                primary: '#A963F8',
                // Design tokens mirroring the templates (light/dark).
                'background-light': '#F7F8FC',
                'background-dark': '#121212',
                'surface-light': '#FFFFFF',
                'surface-dark': '#1E1E1E',
                'text-primary-light': '#1C1C1E',
                'text-primary-dark': '#E4E4E4',
                'text-secondary-light': '#6B7280',
                'text-secondary-dark': '#9CA3AF',
                'border-light': '#E5E7EB',
                'border-dark': '#374151',

                // Legacy tokens kept for backward compatibility with current components.
                light: {
                    primaryColor: '#4F46E5', // gradient start (light)
                    primaryColorSecond: '#9333EA', // gradient end (light)
                    bgColor: '#F7F8FC',
                    bgLightDarkColor: '#FFFFFF',
                    textColorBase: '#1C1C1E',
                    textColorDark: '#000000',
                    linkColor: '#6d28d9',
                    borderColor: '#E5E7EB',
                    heroBG: '#F3F4F6',
                    inputColor: '#F3F4F6',
                    grayLight: '#F3F4F6',
                    grayDark: '#D1D5DB',
                    surface: '#FFFFFF',
                },
                dark: {
                    primaryColor: '#1F2937', // gradient start (dark)
                    primaryColorSecond: '#374151', // gradient end (dark)
                    bgColor: '#121212',
                    bgLightDarkColor: '#1E1E1E',
                    textColorBase: '#E4E4E4',
                    textColorDark: '#FFFFFF',
                    linkColor: '#a78bfa',
                    borderColor: '#374151',
                    heroBG: '#171717',
                    inputColor: '#1e293b',
                    grayLight: '#F3F4F6',
                    grayDark: '#737373',
                    surface: '#1E1E1E',
                },
            },
            keyframes: {
                'accordion-down': {
                    from: { height: '0' },
                    to: { height: 'var(--radix-accordion-content-height)' },
                },
                'accordion-up': {
                    from: { height: 'var(--radix-accordion-content-height)' },
                    to: { height: '0' },
                },
            },
            animation: {
                'accordion-down': 'accordion-down 0.2s ease-out',
                'accordion-up': 'accordion-up 0.2s ease-out',
            },
        },
        fontFamily: {
            jakarta: ['Plus Jakarta Sans', 'ui-sans-serif', 'system-ui'],
        },
        fontWeight: {
            normal: 400,
            medium: 500,
            semibold: 600,
            bold: 700,
            extraBold: 800,
        },
    },
    plugins: [
        function ({ addBase }) {
            addBase({
                ':root': {
                    '--primary-color': '#4F46E5',
                    '--primary-color-second': '#9333EA',
                    '--sidebar-bg-color': '#FFFFFF',
                    '--bg-primary-color': '#F7F8FC',
                    '--bg-transparent': 'transparent',
                    '--bg-light-dark-color': '#FFFFFF',
                    '--bg-secondary-color': '#FFFFFF',
                    '--bg-dark-to-white-color': '#2E2D2D',
                    '--bg-barn-red-color': '#8D2626',
                    '--bg-border-color': '#E5E7EB',
                    '--bg-user-text-color': '#F1F1F1',
                    '--bg-ai-bot-text-color': '#FBFAFA',
                    '--bg-hover-color': '#ECECEC',
                    '--bg-icon-color': '#E7E7E7',
                    '--bg-track-color': '#DBDBDB',
                    '--text-color-base': '#1C1C1E',
                    '--text-color-secondary': '#8F8F8F',
                    '--text-color-dark': '#000000',
                    '--text-color-dark-second': '#393939',
                    '--text-color-dark-third': '#2F2F2F',
                    '--text-color-dark-fourth': '#ffffff',
                    '--text-color-dark-fifth': '#3958C4',
                    '--link-color': '#6d28d9',
                    '--hero-bg': '#f3f4f6',
                    '--input-color': '#f3f4f6',
                    '--gray-light': '#f3f4f6',
                    '--gray-dark': '#d1d5db',
                    '--surface': '#FFFFFF',
                },
                '.light-theme': {
                    '--primary-color': '#4F46E5',
                    '--primary-color-second': '#9333EA',
                    '--sidebar-bg-color': '#FFFFFF',
                    '--bg-primary-color': '#F7F8FC',
                    '--bg-transparent': 'transparent',
                    '--bg-light-dark-color': '#FFFFFF',
                    '--bg-secondary-color': '#FFFFFF',
                    '--bg-dark-to-white-color': '#2E2D2D',
                    '--bg-barn-red-color': '#8D2626',
                    '--bg-border-color': '#E5E7EB',
                    '--bg-user-text-color': '#F1F1F1',
                    '--bg-ai-bot-text-color': '#FBFAFA',
                    '--bg-hover-color': '#ECECEC',
                    '--bg-icon-color': '#E7E7E7',
                    '--bg-track-color': '#DBDBDB',
                    '--text-color-base': '#1C1C1E',
                    '--text-color-secondary': '#8F8F8F',
                    '--text-color-dark': '#000000',
                    '--text-color-dark-second': '#393939',
                    '--text-color-dark-third': '#2F2F2F',
                    '--text-color-dark-fourth': '#ffffff',
                    '--text-color-dark-fifth': '#3958C4',
                    '--link-color': '#6d28d9',
                    '--hero-bg': '#f3f4f6',
                    '--input-color': '#f3f4f6',
                    '--gray-light': '#f3f4f6',
                    '--gray-dark': '#d1d5db',
                },
                '.dark-theme': {
                    '--primary-color': '#1F2937',
                    '--primary-color-second': '#374151',
                    '--sidebar-bg-color': '#1E1E1E',
                    '--bg-primary-color': '#121212',
                    '--bg-transparent': 'transparent',
                    '--bg-light-dark-color': '#1E1E1E',
                    '--bg-secondary-color': '#1E1E1E',
                    '--bg-dark-to-white-color': '#ffffff',
                    '--bg-barn-red-color': '#A12B2B',
                    '--bg-border-color': '#374151',
                    '--bg-user-text-color': '#2D3748',
                    '--bg-ai-bot-text-color': '#1E1E1E',
                    '--bg-hover-color': '#2D3748',
                    '--bg-icon-color': '#1F2937',
                    '--bg-track-color': '#313131',
                    '--text-color-base': '#E4E4E4',
                    '--text-color-secondary': '#9CA3AF',
                    '--text-color-dark': '#ffffff',
                    '--text-color-dark-second': '#959595',
                    '--text-color-dark-third': '#D0D0D0',
                    '--text-color-dark-fourth': '#2E2D2D',
                    '--text-color-dark-fifth': '#4C68CB',
                    '--link-color': '#a78bfa',
                    '--hero-bg': '#171717',
                    '--input-color': '#1e293b',
                    '--gray-light': '#f3f4f6',
                    '--gray-dark': '#737373',
                },
            })
        },
        require('tailwindcss-animate'),
    ],
}
